pt:
  mins: [2., 4., 6., 8., 10., 14.]
  maxs: [4., 6., 8., 10., 14., 23.5]

ML_selections:
  mins: [0.85, 0.85, 0.85, 0.85, 0.85, 0.85]
  maxs: [0.995, 0.995, 0.995, 0.995, 0.995, 0.995]
  steps: [0.005, 0.005, 0.005, 0.005, 0.005, 0.005]

channel:
  name: B0ToDPi
  pdg_code: 511  # PDG code of the beauty meson
  br:
    b0_todminuspi: 0.00251
    dplus_tokpipi: 0.0938

inputs:
  fonll:
    file_name: inputs/predictions/FONLL/BhadrNNPDF30.root
    graph_name: gBhadrNNPDF30
    frag_frac: 1 # B hadron to B0/B+ fragmentation fraction
  acc_eff_presel:
    file_name: efficiency/finer_pt_high_pt/efficiency_i3_i4_from_bdt_test.root
    hist_name: h_eff_trigger
  zorro:
    file_names: [ # AnalysisResults.root files of preliminary workflow
            inputs/24_separate/data/AnalysisResults_LHC23_pass4_skimmed.root,
            inputs/24_separate/data/AnalysisResults_LHC24_pass1_skimmed.root,
            inputs/24ao/AnalysisResults_LHC24ao_pass1_skimmed.root
            ]
    folder_name: hf-data-creator-charm-had-pi-reduced/Zorro
    triggers_of_interest: ['fHfBeauty4P']
    h_collisions_path: 'hf-candidate-creator-3prong/hCollisions'
    tvx_cross_section: 59400000000 # pb
  mc: # this is MC with Bkg and ModelApplied !
    file_names: [
        ML/application/default_finer_pt_high_pt/LHC24i3_B0ToDPi_pT_2_6_ModelApplied.parquet.gzip,
        ML/application/default_finer_pt_high_pt/LHC24i3_B0ToDPi_pT_6_14_ModelApplied.parquet.gzip,
        ML/application/default_finer_pt_high_pt/LHC24i3_B0ToDPi_pT_14_100_ModelApplied.parquet.gzip,
        ML/application/default_finer_pt_high_pt/LHC24i4_B0ToDPi_pT_2_6_ModelApplied.parquet.gzip,
        ML/application/default_finer_pt_high_pt/LHC24i4_B0ToDPi_pT_6_14_ModelApplied.parquet.gzip,
        ML/application/default_finer_pt_high_pt/LHC24i4_B0ToDPi_pT_14_100_ModelApplied.parquet.gzip,
       ]
  real_data: # this is real data with ModelApplied !
    file_names: [
          ML/application/default_finer_pt_high_pt/LHC24_pass1_B0ToDPi_pT_2_6_ModelApplied.parquet.gzip,
          ML/application/default_finer_pt_high_pt/LHC24_pass1_B0ToDPi_pT_6_14_ModelApplied.parquet.gzip,
          ML/application/default_finer_pt_high_pt/LHC24_pass1_B0ToDPi_pT_14_100_ModelApplied.parquet.gzip,
          ML/application/default_finer_pt_high_pt/LHC23_pass4_B0ToDPi_pT_2_6_ModelApplied.parquet.gzip,
          ML/application/default_finer_pt_high_pt/LHC23_pass4_B0ToDPi_pT_6_14_ModelApplied.parquet.gzip,
          ML/application/default_finer_pt_high_pt/LHC23_pass4_B0ToDPi_pT_14_100_ModelApplied.parquet.gzip,
          ML/application/default_finer_pt_high_pt/LHC24ao_B0ToDPi_pT_2_6_ModelApplied.parquet.gzip,
          ML/application/default_finer_pt_high_pt/LHC24ao_B0ToDPi_pT_6_14_ModelApplied.parquet.gzip,
          ML/application/default_finer_pt_high_pt/LHC24ao_B0ToDPi_pT_14_100_ModelApplied.parquet.gzip
        ]

fit_bkg:
  mass_range_to_exclude: [5.15, 5.4]
  mass_limits_for_fit: [4.9, 5.66]
  bkg_funcs: [["chebpol2"], ["chebpol2"], ["chebpol2"], ["chebpol2"], ["chebpol2"], ["chebpol2"]]
  nbins: 76
  use_bkg_templ: True
  correlated_bkgs:
    - name: '$\mathrm{B^0 \rightarrow D^{*-}\pi^+ \rightarrow D^-\pi^+\{\pi^0, \gamma\}}$'
      beauty_id: 511
      charm_id: 824
      br_pdg: 8.0591084e-05 # 2.66e-3 * (30.7e-2 + 1.6e-2) * 9.38e-2
      br_sim: 0.04589871504152629 # 0.333333333333 * (30.7e-2 + 1.6e-2) * 0.42630385487528344

    - name: '$\mathrm{B^0 \rightarrow D^{*-}\pi^+ \rightarrow D^0\pi^-\pi^+}$'
      beauty_id: 511
      charm_id: 413
      br_pdg: 7.10783654e-05 # 2.66e-3 * 67.7e-2 * 3.947e-2
      br_sim: 0.20515151515110489 # 0.333333333333 * 67.7e-2 * 0.90909090909

    - name: '$\mathrm{B_s^0 \rightarrow D_s^-\pi^+ \rightarrow K^+K^-\pi^+\pi^+}$'
      beauty_id: 531
      charm_id: 431
      br_pdg: 0.000160026 # 2.98e-3 * 5.37e-2 
      br_sim: 0.8 # 0.8 * (0.52380952381 + 0.47619047619)

    - name: '$\mathrm{\Lambda_b^0 \rightarrow \Lambda_c^+\pi^- \rightarrow pK^-\pi^+\pi^-}$'
      beauty_id: 5122
      charm_id: 4122
      br_pdg: 0.00030576 # 4.9e-3 * 6.24e-2
      br_sim: 0.2710551790900291 # 0.8 * 0.33881897386253634

    - name: '$\mathrm{B^0 \rightarrow D^-\rho^+ \rightarrow D^-\pi^+\{\pi^0, \gamma\}}$'
      beauty_id: 511
      charm_id: 411
      br_pdg: 0.00071288 # 7.6e-3 * 9.38e-2
      br_sim: 0.042630385487528344  # 0.1 * 0.42630385487528344

  signal_br:
    pdg: 0.000235438 # 2.51e-3 * 9.38e-2
    sim: 0.17052154195011338 # 0.4 * 0.42630385487528344
  verbosity: 0

zfit_cpus:
  intra: 30
  inter: 30

output:
  outdir: ML/optimisation/finer_pt_high_pt
  sidebands_fit_dir: sidebands_fit
  scan_results_file_name: scan_results.root