reference_fits: ../../fit/anchored_pidvars/B0_mass_anchor_pidvars_chebpol2.root
    
inputs:
    data: [../../ML/applications/anchored_pid/LHC23_pass4_B0ToDPi_pT_2_6_ModelApplied.parquet.gzip,
           ../../ML/applications/anchored_pid/LHC23_pass4_B0ToDPi_pT_6_14_ModelApplied.parquet.gzip,
           ../../ML/applications/anchored_pid/LHC23_pass4_B0ToDPi_pT_14_100_ModelApplied.parquet.gzip,
           ../../ML/applications/anchored_pid/LHC24_pass1_B0ToDPi_pT_2_6_ModelApplied.parquet.gzip,
           ../../ML/applications/anchored_pid/LHC24_pass1_B0ToDPi_pT_6_14_ModelApplied.parquet.gzip,
           ../../ML/applications/anchored_pid/LHC24_pass1_B0ToDPi_pT_14_100_ModelApplied.parquet.gzip,
           ../../ML/applications/anchored_pid/LHC24ao_pass1_B0ToDPi_pT_2_6_ModelApplied.parquet.gzip,
           ../../ML/applications/anchored_pid/LHC24ao_pass1_B0ToDPi_pT_6_14_ModelApplied.parquet.gzip,
           ../../ML/applications/anchored_pid/LHC24ao_pass1_B0ToDPi_pT_14_100_ModelApplied.parquet.gzip]
    mc: [../../ML/applications/anchored_pid/LHC24i3_B0ToDPi_pT_2_6_ModelApplied.parquet.gzip,
         ../../ML/applications/anchored_pid/LHC24i3_B0ToDPi_pT_6_14_ModelApplied.parquet.gzip,
         ../../ML/applications/anchored_pid/LHC24i3_B0ToDPi_pT_14_100_ModelApplied.parquet.gzip,
         ../../ML/applications/anchored_pid/LHC24i4_B0ToDPi_pT_2_6_ModelApplied.parquet.gzip,
         ../../ML/applications/anchored_pid/LHC24i4_B0ToDPi_pT_6_14_ModelApplied.parquet.gzip,
         ../../ML/applications/anchored_pid/LHC24i4_B0ToDPi_pT_14_100_ModelApplied.parquet.gzip]

    cutset: ../../config/cutset.yaml

output_dir: systematics/raw_yields/outputs              # output directory
save_all_fits: true                                     # whether to save all fits figures
output_dir_fits: fits                                   # append to output_dir

correlated_bkgs:
  - name: '$\mathrm{B^0 \rightarrow D^{*-}\pi^+ \rightarrow D^-\pi^+\{\pi^0, \gamma\}}$'
    beauty_id: 511
    charm_id: 824
    br_pdg: 8.0591084e-05 # 2.66e-3 * (30.7e-2 + 1.6e-2) * 9.38e-2
    br_sim: 0.04589871504152629 # 0.333333333333 * (30.7e-2 + 1.6e-2) * 0.42630385487528344

  - name: '$\mathrm{B^0 \rightarrow D^{*-}\pi^+ \rightarrow D^0\pi^-\pi^+}$'
    beauty_id: 511
    charm_id: 413
    br_pdg: 7.10783654e-05 # 2.66e-3 * 67.7e-2 * 3.947e-2
    br_sim: 0.20515151515110489 # 0.333333333333 * 67.7e-2 * 0.90909090909

  - name: '$\mathrm{B_s^0 \rightarrow D_s^-\pi^+ \rightarrow K^+K^-\pi^+\pi^+}$'
    beauty_id: 531
    charm_id: 431
    br_pdg: 0.000160026 # 2.98e-3 * 5.37e-2 
    br_sim: 0.8 # 0.8 * (0.52380952381 + 0.47619047619)

  - name: '$\mathrm{\Lambda_b^0 \rightarrow \Lambda_c^+\pi^- \rightarrow pK^-\pi^+\pi^-}$'
    beauty_id: 5122
    charm_id: 4122
    br_pdg: 0.00030576 # 4.9e-3 * 6.24e-2
    br_sim: 0.2710551790900291 # 0.8 * 0.33881897386253634

  - name: '$\mathrm{B^0 \rightarrow D^-\rho^+ \rightarrow D^-\pi^+\{\pi^0, \gamma\}}$'
    beauty_id: 511
    charm_id: 411
    br_pdg: 0.00071288 # 7.6e-3 * 9.38e-2
    br_sim: 0.042630385487528344  # 0.1 * 0.42630385487528344

signal_br:
  pdg: 0.000235438 # 2.51e-3 * 9.38e-2
  sim: 0.17052154195011338 # 0.4 * 0.42630385487528344

multitrial:
    pt_bins: [0]                                        # list of pt bins, set null if you want to keep them all
    mins: [4.90, 4.92, 4.96]                            # lower fit limit
    maxs: [5.66, 5.64, 5.62]                            # upper fit limit
    sgn_funcs: [[gaussian]]                             # signal functions
    bkg_funcs: [[expo], [chebpol2]]                     # bkg functions
    sigma: [free]                                       # free, fixed, fixed_plus_unc, fixed_minus_unc, fixed_plus_XX_perc, fixed_minus_XX_perc
    mean: [free]                                        # free, fixed, fixed_plus_unc, fixed_minus_unc, fixed_plus_XX_perc, fixed_minus_XX_perc
    use_bkg_templ: [true]                               # use bkg template --> keep always true
    bkg_templ_opt: [1]                                  # bkg template option: # 0 -> all separated, 1 -> weighted average (faster)
    fix_correlated_bkg_to_signal: [true, false]         # fix relative normalisation of correlated backgrounds to signal
    bincounting_nsigma: []                              # nsigmas for bin counting raw yield extraction

assigned_syst: [0.1,]                                   # assigned systematic uncertainties
