rawyield_file: fit/outputs/default/B0_mass23_24_full_dataset.root
efficiency_file: efficiency/efficiency_i3_i4_from_bdt_test.root
output_file: cross_section/cross_section_full_23_24_with_bc_cuts.root

lumi:
  analysis_results_files: [
                          'inputs/24_separate/data/AnalysisResults_LHC24_pass1_skimmed.root',
                          'inputs/24_separate/data/AnalysisResults_LHC23_pass4_skimmed.root'
                          ]
  zorro_folder: 'hf-data-creator-charm-had-pi-reduced/Zorro'
  folder_bc_cuts: 'bc-selection-task'
  triggers_of_interest: ['fHfBeauty4P']
  h_collisions_path: 'hf-candidate-creator-3prong/hCollisions'
  tvx_cross_section: 59400000000 # pb
  lumi_before_bc_cuts: 3035880803644.0  # 13260200827/0.005 + 383840638244    # Can be null for extracting it from analysis_results_files
  lumi_after_bc_cuts: 2382365588911.0   # 10354007744/0.005 + 311564040111    # Can be null for extracting it from analysis_results_files

br:
  b0_todminuspi: 0.00251
  dplus_tokpipi: 0.0938
